name: Clear Commit History
on:
  workflow_dispatch:

jobs:
  clear-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset History to 1 Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@://github.com"
          
          git checkout --orphan temp_clean_branch
          git add -A
          git commit -m "Full project implementation"
          
          if git show-ref --verify --quiet refs/heads/main; then
            git branch -D main
            git branch -m main
            git push origin main --force
          else
            git branch -D master
            git branch -m master
            git push origin master --force
          fi
